### ISSUE TITLE
Does not show any messages

### ISSUE THREAD

**Issue by clyfe** [kamituel/systems-toolbox-chrome#8]
I open the extension in developer tools and no messages are being shown.

In Chromium I get an error when I open it:
https://dl.dropboxusercontent.com/u/2597631/temp/err.jpg

In Chrome I don't get that error, but it still stays empty always, showing nothing:
https://dl.dropboxusercontent.com/u/2597631/temp/empty.jpg

**Comment by kamituel** [comment]
I think I fixed it - but for that to work @matthiasn needs to make a release with this merged: https://github.com/matthiasn/systems-toolbox/pull/32 (or you can install it locally for now).
